# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
image: node:14

options:
  docker: true

definitions:
  steps:
    - step: &install
        name: install
        script:
          - npm -v
          - node -v
          - npm run clean
          - npm install
        artifacts: # defining the artifacts to be passed to each future step.
          - node_modules/**
    - step: &generate_swagger
        name: generate_swagger
        script:
          - npm run generate-swagger:staging
        artifacts: # defining the artifacts to be passed to each future step.
          - src/generated/**
    - step: &build
        name: build
        script:
          - npm run build:staging
        artifacts:
          - dist/**
    - step: &lint
        name: lint
        script:
          - npm run lint-and-fix
    - step: &deploy_stagging
        trigger: manual
        name: Deploy To Stagging
        deployment: Staging
        caches:
          - node
        script:
          - npm install firebase-tools
          - firebase deploy --token $FIREBASE_TOKEN  --project sciencewings-webapp --non-interactive
pipelines:
  default:
    - step: *install
    - step: *generate_swagger
    - step: *build
    # - step: *lint
    - step: *deploy_stagging
  branches:
    develop/*:
      - step: *install
      - step: *generate_swagger
      - step: *build
      - step: *lint
      - step: *deploy_stagging
    feature/*:
      - step: *install
      - step: *generate_swagger
      - step: *build
      - step: *lint
    bugfix/*:
      - step: *install
      - step: *generate_swagger
      - step: *build
      - step: *lint
